function mat = vectorImage(w,numregions,map,symtype)

% returns a colormap of the matrices represented by vectors w1,w2,w3.
% Since the matrix is skew symmetric, the colormap only includes the
% upper triangular part.  
% INPUTS: 
% w:           vector that will be transformed into its matrix version
% numregions:  number of ROIs
% map:         colormap to be used, should be a nx3 array
% symtype:     the symmetry type for the matirx, can be 1 if you want
%              symmetric, -1 if you want anti-symmetric
%OUTPUTS:
% mat:         an image giving a colormap based representation of relative
%              matrix values for the matrix generated by w.


matrix = zeros(numregions,numregions); %creates matrix to be filled
count = 1;                             % used for indexing elements in w to
                                       % be placed in matrix.
                                       
for i =1:numregions;                   % places values of w into upper 
                                       % triangluar half, places either -w
                                       % or w in lower depending on whether
                                       % symtype was 1 or -1
   for j = i+1: numregions;
        matrix(i,j) = w(count);
        matrix(j,i) = symtype*w(count);
        count = count+1; 
        end   
   end

mat = image(matrix,'CDataMapping','scaled'); % creates image with specified 
colormap(map);                               % colormap "map"
colorbar;
end